security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        admin_users:
            entity:
                class: App\Entity\Customer\AdminUser
                property: email

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: admin_users
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                default_target_path: admin_dashboard
            logout:
                path: admin_logout
                target: admin_login
                enable_csrf: true

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/yeni/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/yeni/admin, roles: ROLE_ADMIN }

when@test:
    security:
        providers:
            test_non_admins:
                memory:
                    users:
                        viewer@example.com:
                            password: 'test-only-not-used-for-form-login'
                            roles: [ROLE_USER]
            test_user_chain:
                chain:
                    providers: [admin_users, test_non_admins]
        firewalls:
            main:
                provider: test_user_chain
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
